spring.application.name=postService
server.port=9020 

spring.datasource.url=jdbc:postgresql://ep-icy-night-awd9n4bw-pooler.c-12.us-east-1.aws.neon.tech/post-service?user=neondb_owner&password=npg_CyhIjoPY3u9A&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CyhIjoPY3u9A


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=linkedin
cloudinary.api-key=673681582867599
cloudinary.api-secret=SdVB5BM084Arj2UWVJs-ybjiOxI