spring.application.name=userService
server.port=9010    
spring.datasource.url=jdbc:postgresql://ep-icy-night-awd9n4bw-pooler.c-12.us-east-1.aws.neon.tech/user-service?user=neondb_owner&password=npg_CyhIjoPY3u9A&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CyhIjoPY3u9A

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
