spring.application.name=userService
server.port=9010    

spring.profiles.active=local

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.refresh.secret=${JWT_REFRESH_SECRET}
jwt.access.expiration-ms=${JWT_ACCESS_EXPIRATION_MS}
jwt.refresh.expiration-ms=${JWT_REFRESH_EXPIRATION_MS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
